### PR TITLE
CI: point action to codecov.xml as generated by pytest-cov

### PR DESCRIPTION
**Pull request by rgommers**
Addresses the issue in https://github.com/mesonbuild/meson-python/pull/657#issuecomment-2265481244

### CODE REVIEW

**Comment by rgommers** [comment]
Okay, that isn't it, no change. This broke something in the last 4 weeks says the dashboard for PRs:

image

It worked 4 weeks ago and doesn't work today, nothing changed on our side. There is zero useful logging in CI (it claims success) or in the dashboard. `codecov-action` didn't change in that time, and neither did `pytest-cov`. One `coverage release (7.6.0) but no relevant open issues. I'll park this for now.

**Comment by dnicolodi** [comment]
Does anyone know hot to get codecov unstuck?

@rgommers Should we switch to something else? coveralls.io seems to be another popular option.

**Comment by rgommers** [comment]
Maybe it fixed itself in the meantime and there's nothing left to do? The percentages are no longer missing and https://app.codecov.io/gh/mesonbuild/meson-python/commits looks like:

image

It seems like the code browser is also up to date again (https://app.codecov.io/gh/mesonbuild/meson-python/blob/main/mesonpy%2F__init__.py). 

> Should we switch to something else? 

I rarely look at codecov, so I'd be fine with anything.

**Comment by dnicolodi** [comment]
I just look at the reports that pop up along the CI tests results. I haven't seen these working in a very long time. Therefore I thought codecov was still broken for us. Do you know how to get these back?

**Comment by rgommers** [comment]
Ah, in https://github.com/mesonbuild/meson-python/settings/installations I now see that the GitHub App is suspended, so that's probably why the notifications don't show up:

image

I don't know what happened though; it can only be re-enabled by an org owner. @jpakkane would you mind hitting the _Configure_ button on that link and then the _Update Access_ one on the next screen?

**Comment by jpakkane** [comment]
We disabled codecov on the main repo because it was too spammy and not really helpful. Should be fixed now.

**Comment by rgommers** [comment]
I think everything is fixed; in the most recent push for gh-681 I see:

image

I'll close this PR.

**Pull request closed without merging**
