### PR TITLE
Prepare release 0.16.0

### PR DESCRIPTION
**Pull request by dnicolodi**
@rgommers Unless you have anything against it I'm going to get this out of the door in the next few days. The pending PRs will be material for 0.17.0

### CODE REVIEW

**Review by rgommers — APPROVED** [review]
Thanks @dnicolodi. I think that covers all the user-visible changes (outside of docs updates).

The one thing I'd consider adding is to note that the docs moved to https://mesonbuild.com/meson-python/. Worth including?

**Comment by rgommers** [comment]
Ah, and: pre-commit has a minor complaint

**Comment by rgommers** [comment]
Do you want to do this release, or do you want me to take care of it? Either way you may want to add your GPG key to `docs/about.rst`?

**Comment by dnicolodi** [comment]
#594 should be mentioned too, probably. I'm not sure mentioning the documentation location change in a changelog that is visible only at the new location is that useful. But I don't have anything against it.

**Comment by rgommers** [comment]
> #594 should be mentioned too, probably

Ah yes, agreed. There are two editable install related entries; this one is deserving of a separate mention indeed.

**Comment by dnicolodi** [comment]
If you have the time for it, I'll appreciate if you could cut the release once the last bits are committed.

**Comment by rgommers** [comment]
Sure, will do. I've been utterly swamped for too long, but I should just make time. Turning off Slack now and will keep working on meson-python for most of today:)

**Comment by dnicolodi** [comment]
Thanks @rgommers! I updated the changelog, PTAL. I think there isn't anything else that we want to include in 0.16.0

**Comment by rgommers** [comment]
LGTM, in it goes.

**Pull request merged**
