### PR TITLE
BUG: fix handling of files installed via install_subdir

### PR DESCRIPTION
**Pull request by dnicolodi**

### CODE REVIEW

**Comment by rgommers** [comment]
This looks happy. It has a bit of overlap with gh-465 - can I review and merge this one first?

**Comment by dnicolodi** [comment]
If the strategy used here work, and moving RPATH handling to meson-python work, #465 is not going to happen. I've the patch for the RPATH handling almost ready. We can merge this and retire #465.

**Comment by dnicolodi** [comment]
I've fixed the RPATH handling in #469 on top of this PR. It seems that we can do without running `meson install` without any drawback, thus we can move forward with the strategy in this PR.

**Review by rgommers — APPROVED** [review]
Thanks @dnicolodi! All LGTM, and I tested a bunch of things with SciPy and Pandas - everything is happy.

**Pull request merged**
