### PR TITLE
DOC/REL: prepare 0.15.0 changelog and release

### PR DESCRIPTION
**Pull request by rgommers**
We accumulated a few important bug fixes and new features, so it seems time for a release.

@dnicolodi I set the date to today - in case it gets merged later, that date should be updated right before the merge.

### CODE REVIEW

**Comment by dnicolodi** [comment]
@rgommers Thanks for working on this. The changelog entries for other releases use the present tense, but the ones for 0.15.0 used the past tense. I took the freedom to fix them to use the present tense and to do some rewording PTAL.

**Comment by rgommers** [comment]
Thanks @dnicolodi, LGTM! Let me just bump the date once more, and then I'll get this release done.

**Comment by dnicolodi** [comment]
Thanks @rgommers. The changelog in the present tense reads a bit strange to me too, but this is how it was started, and I think there is value in keeping it all in the same form.

**Comment by rgommers** [comment]
Yes, agreed. We may want to change it at some point, but let's consider it only if we make other changes like adding change categories (bug fix, enhancement, backwards compatibility, etc.).

**Pull request merged**
