### PR TITLE
ENH: use tomllib on Python 3.11+

### PR DESCRIPTION
**Pull request by henryiii**
Use tomllib if available.

### CODE REVIEW

**Comment by rgommers** [comment]
@henryiii no those have been happening on other PRs and we need to sort them out. This PR LGTM, thanks for making it!

**Comment by rgommers** [comment]
Eh wait, let me double check. There are more failures now, not just the 2-3 distros from before.

**Review by FFY00 — APPROVED** [review]
Thanks!

**Comment by FFY00** [comment]
The change looks good, we just need to figure out what is triggering these CI fails.

**Pull request merged**
