### PR TITLE
Prepare release 0.13.2

### PR DESCRIPTION
**Pull request by dnicolodi**
@rgommers Feel free to tag the release when you have a minute.

### CODE REVIEW

**Review by rgommers — APPROVED** [review]
Thanks @dnicolodi! Will merge this now and finalize the release later tonight.

**Comment by rgommers** [comment]
Release is up now.

**Comment by rgommers** [comment]
@dnicolodi I replaced the `0.13.2` tag you pushed with a GPG-signed one also containing the changelog entries: https://github.com/mesonbuild/meson-python/releases/tag/0.13.2. This is documented in https://meson-python.readthedocs.io/en/latest/contributing/release-process.html.

I'll open a PR to tweak the PyPI upload instructions, because PyPI no longer supports GPG signature upload, and in fact emails you that they were discarded if you try.

**Comment by dnicolodi** [comment]
I didn't intend to push a tag. I don't think Github allows to push tags via merge requests.

**Comment by rgommers** [comment]
No worries at all. I thought the same - no tags via PRs, so it's a little unclear what happened. It's even possible that I did it, and that since it was an unsigned tag the GitHub UI reported it as coming from you because it was attached to one of your commits.

**Pull request merged**
