### PR TITLE
ENH: Add install-tags filtering for wheel generation (updated)

### PR DESCRIPTION
**Pull request by peter-urban**
This is a PR for https://github.com/mesonbuild/meson-python/issues/68
It is a continuation of  (and should probably replace) @Brishen's PR https://github.com/mesonbuild/meson-python/pull/267 which used my code, but has not been updated (since two weeks) to include the suggestions/changes made in reaction to @FFY00's comments.

### CODE REVIEW

**Comment by FFY00** [comment]
Hi @peter-urban, thank you! This is just missing a test, and applying the changes from pre-commit. Could you either tick the "allow maintainers to make changes" box in this PR, so that I can push that, or apply the pre-commit changes yourself and add the test below to `test_project.toml`. After that, we can merge :blush: 

```python
def test_install_tags(package_purelib_and_platlib, tmp_path_session):
    project = mesonpy.Project(
        package_purelib_and_platlib,
        tmp_path_session,
        meson_args={
            'install': ['--tags', 'purelib'],
        }
    )
    assert project.is_pure
```

**Comment by peter-urban** [comment]
@FFY00 thank :-) I merged with main again and added the test you suggested (I assume you meant test_project.py) 
I wanted to give you write access, but for some reason I cannot see the "allow maintainers to make changes" box.  (Maybe because I merge from a fork that belongs to an "organization" and not to my personal account) So I just hope the changes are ok now?

Looking forward to get this merged!

**Comment by FFY00** [comment]
Yeah :sweat_smile:

Thanks! I think it's just missing the pre-commit changes. You can run `pre-commit run --all-files` and commit the changes.

**Comment by peter-urban** [comment]
thanks, first time I work with pre-commit :-)

**Comment by FFY00** [comment]
No worries. Thank you for getting this through.

The Debian CI failure is unrelated. Let's just wait to see if the rest of the CI is green, and then we can merge :rocket:

**Comment by FFY00** [comment]
Ugh, seems now we have conflicts. I am just gonna open a new PR and fix it myself, as I don't want to bother you.

**Comment by FFY00** [comment]
Closed in favor of #288. Thank you so much for the contribution @peter-urban!

**Comment by peter-urban** [comment]
Hi, I can fix it in half an hour and it doesn't bother me actually. But if you find it eas easier, it is no problem

Gesendet von Outlook für Android<https://aka.ms/AAb9ysg>
________________________________

**Pull request closed without merging**
